# Source: onap/charts/mariadb-galera/templates/pv.yaml
kind: PersistentVolume
apiVersion: v1
metadata:
  name: onap-mariadb-galera--0
  #namespace: onap
  labels:
    app.kubernetes.io/name: mariadb-galera
    helm.sh/chart: mariadb-galera-10.0.0
    app.kubernetes.io/instance: onap
    app.kubernetes.io/managed-by: Helm
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy:
  storageClassName: "onap-mariadb-galera-data"
  hostPath:
    path: /dockerdata-nfs/deployment-1670599359/onap/mariadb-galera/data-0
