# Source: onap/charts/sdnc/charts/elasticsearch/charts/master/templates/pv.yaml
kind: PersistentVolume
apiVersion: v1
metadata:
  name: onap-sdnrdb-master-pv-0
  namespace: onap
  labels:
    app.kubernetes.io/name: sdnrdb
    helm.sh/chart: master-10.0.0
    app.kubernetes.io/instance: onap
    app.kubernetes.io/managed-by: Helm
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "onap-sdnrdb-master-pv"
  hostPath:
    path: /dockerdata-nfs/deployment-1670599359/onap/elastic-master-0
