# Source: onap/charts/sdnc/charts/elasticsearch/charts/master/templates/statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: onap-sdnrdb-master
  namespace: onap
  labels:
    app.kubernetes.io/name: sdnrdb
    helm.sh/chart: master-10.0.0
    app.kubernetes.io/instance: onap
    app.kubernetes.io/managed-by: Helm
    discovery: sdnrdb-cluster
    role: master
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: sdnrdb
      app.kubernetes.io/instance: onap
      discovery: sdnrdb-cluster
      role: master
  serviceName: onap-sdnrdb-master
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sdnrdb
        helm.sh/chart: master-10.0.0
        app.kubernetes.io/instance: onap
        app.kubernetes.io/managed-by: Helm
        discovery: sdnrdb-cluster
        role: master
      name: sdnrdb
    spec:
      imagePullSecrets:
      - name: "onap-docker-registry-key"
      securityContext:
        fsGroup: 1001
      initContainers:
      ## Image that performs the sysctl operation to modify Kernel settings (needed sometimes to avoid boot errors)
      - name: sysctl
        image: docker.io/busybox:1.34.1
        imagePullPolicy: IfNotPresent
        command:
        - /bin/sh
        - -c
        - |
          set -o errexit
          set -o pipefail
          set -o nounset
          sysctl -w vm.max_map_count=262144 && sysctl -w fs.file-max=65536
        securityContext:
          privileged: true
      - name: volume-permissions
        image: docker.io/busybox:1.34.1
        imagePullPolicy: IfNotPresent
        command:
        - /bin/sh
        - -c
        - |
          chown -R 1001:1001 //bitnami/elasticsearch/data
        securityContext:
          runAsUser: 0
        volumeMounts:
        - name: data
          mountPath: "/bitnami/elasticsearch/data"
      containers:
      - name: sdnrdb-master
        image: docker.io/bitnami/elasticsearch:7.9.3
        imagePullPolicy: IfNotPresent
        securityContext:
          runAsUser: 1001
        env:
        - name: BITNAMI_DEBUG
          value: "false"
        - name: ELASTICSEARCH_CLUSTER_NAME
          value: sdnrdb-cluster
        - name: ELASTICSEARCH_CLUSTER_HOSTS
          value: sdnrdb-discovery
        - name: ELASTICSEARCH_CLUSTER_MASTER_HOSTS
          value: onap-sdnrdb-master-0
        - name: ELASTICSEARCH_MINIMUM_MASTER_NODES
          value: "1"
        - name: ELASTICSEARCH_HEAP_SIZE
          value: "128m"
        - name: ELASTICSEARCH_IS_DEDICATED_NODE
          value: "no"
        - name: ELASTICSEARCH_NODE_TYPE
          value: "master"
        ports:
        - containerPort: 9300
          name: http-transport
        resources:
          limits:
            cpu: 250m
            memory: 1536Mi
          requests:
            cpu: 5m
            memory: 310Mi
        volumeMounts:
        - name: data
          mountPath: /bitnami/elasticsearch/data
      volumes:
  volumeClaimTemplates:
  - metadata:
      name: "data"
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: onap-sdnrdb-master-pv
      resources:
        requests:
          storage: "8Gi"
