# Source: onap/charts/postgres/templates/pvc-replica.yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: onap-postgres-replica
  namespace: onap
  labels:
    app: onap-postgres
    chart: "postgres-10.0.0"
    release: "onap"
    heritage: "Helm"
    name: onap-postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: "onap-postgres-replica"
