# Source: onap/charts/postgres/templates/service-common.yaml
apiVersion: v1
kind: Service
metadata:
  name: pgset
  namespace: onap
  labels:
    app: postgres
    chart: postgres-10.0.0
    release: onap
    heritage: Helm
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      name: tcp-postgres
  selector:
    app: postgres
    release: onap
