# Source: onap/charts/postgres/templates/service-primary.yaml
apiVersion: v1
kind: Service
metadata:
  name: tcp-pgset-primary
  namespace: onap
  labels:
    app: postgres-primary
    chart: postgres-10.0.0
    release: onap
    heritage: Helm
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      name: tcp-postgres
  selector:
    name: "pgset-primary"
    release: onap
