# Source: onap/charts/policy/charts/policy-clamp-ac-pf-ppnt/charts/certInitializer/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: onap-policy-clamp-ac-pf-ppnt-cert-initializer-add-config
  namespace: onap
  labels:
    app.kubernetes.io/name: policy-clamp-ac-pf-ppnt-cert-initializer
    helm.sh/chart: certInitializer-10.0.0
    app.kubernetes.io/instance: onap
    app.kubernetes.io/managed-by: Helm
data:
  retrieval_check.sh: |
    #!/bin/sh

    echo "*** retrieving passwords for certificates"
    export $(/opt/app/aaf_config/bin/agent.sh local showpass \
      policy@policy.onap.org policy | grep '^c' | xargs -0)
    if [ -z "$cadi_keystore_password_p12" ]
    then
      echo " /!\ certificates retrieval failed"
      exit 1
    fi
    echo "*** password retrieval succeeded"
  aaf-add-config.sh: |
    echo "export KEYSTORE='/opt/app/osaaf/local/org.onap.policy.p12'" > /opt/app/osaaf/local/.ci; echo "export KEYSTORE_PASSWD='${cadi_keystore_password_p12}'" >> /opt/app/osaaf/local/.ci; chown -R 100:101 $(dirname /opt/app/osaaf/local);
