# Source: onap/charts/strimzi/templates/strimzi-kafka-admin-user.yaml
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: strimzi-kafka-admin
  namespace: onap
  labels:
    strimzi.io/cluster: onap-strimzi
spec:
  authentication:
    type: scram-sha-512
  authorization:
    type: simple
    acls:
    - resource:
        type: group
        name: onap-group
      operation: Read
