# Source: onap/charts/sdnc/charts/sdnc-web/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: onap-sdnc-web
  namespace: onap
  labels:
    app.kubernetes.io/name: sdnc-web
    helm.sh/chart: sdnc-web-10.0.0
    app.kubernetes.io/instance: onap
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: sdnc-web
      app.kubernetes.io/instance: onap
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sdnc-web
        helm.sh/chart: sdnc-web-10.0.0
        app.kubernetes.io/instance: onap
        app.kubernetes.io/managed-by: Helm
      name: sdnc-web
    spec:
      initContainers:
      - name: sdnc-web-cert-initializer-readiness
        image: nexus3.onap.org:10001/onap/oom/readiness:3.0.1
        imagePullPolicy: IfNotPresent
        securityContext:
          runAsUser: 100
          runAsGroup: 65533
        command:
        - /app/ready.py
        args:
        - --container-name
        - aaf-locate
        - --container-name
        - aaf-cm
        - --container-name
        - aaf-service
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 3m
            memory: 20Mi
      - name: sdnc-web-aaf-config
        image: nexus3.onap.org:10001/onap/aaf/aaf_agent:2.1.20
        imagePullPolicy: IfNotPresent
        securityContext:
          runAsUser: 0
        volumeMounts:
        - mountPath: /opt/app/osaaf
          name: onap-sdnc-web-aaf-config
        - mountPath: /opt/app/aaf_config/cert/truststoreONAPall.jks.b64
          name: aaf-agent-certs
          subPath: truststoreONAPall.jks.b64
        - mountPath: /opt/app/aaf_config/cert/truststoreONAP.p12.b64
          name: aaf-agent-certs
          subPath: truststoreONAP.p12.b64
        - name: aaf-add-config
          mountPath: /opt/app/aaf_config/bin/retrieval_check.sh
          subPath: retrieval_check.sh
        - name: aaf-add-config
          mountPath: /opt/app/aaf_config/bin/aaf-add-config.sh
          subPath: aaf-add-config.sh
        command:
        - sh
        - -c
        - |
          /opt/app/aaf_config/bin/agent.sh
          . /opt/app/aaf_config/bin/retrieval_check.sh
          /opt/app/aaf_config/bin/aaf-add-config.sh
        env:
        - name: APP_FQI
          value: "sdnc@sdnc.onap.org"
        - name: aaf_locate_url
          value: "https://aaf-locate.onap:8095"
        - name: aaf_locator_container_ns
          value: "onap"
        - name: aaf_locator_container
          value: "oom"
        - name: aaf_locator_fqdn
          value: "sdnc"
        - name: aaf_locator_app_ns
          value: "org.osaaf.aaf"
        - name: DEPLOY_FQI
          valueFrom:
            secretKeyRef:
              name: onap-sdnc-web-cert-initializer-deployer-creds
              key: login
        - name: DEPLOY_PASSWORD
          valueFrom:
            secretKeyRef:
              name: onap-sdnc-web-cert-initializer-deployer-creds
              key: password
              #Note: want to put this on Nodes, eventually
        - name: cadi_longitude
          value: "-72.0"
        - name: cadi_latitude
          value: "38.0"
          #Hello specific.  Clients don't don't need this, unless Registering with AAF Locator
        - name: aaf_locator_public_fqdn
          value: "sdnc.onap.org"
      - name: sdnc-web-readiness
        image: nexus3.onap.org:10001/onap/oom/readiness:3.0.1
        imagePullPolicy: IfNotPresent
        command:
        - /app/ready.py
        args:
        - --container-name
        - sdnc
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
      containers:
      - name: sdnc-web
        image: nexus3.onap.org:10001/onap/sdnc-web-image:2.2.5
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8443
          name: sdnc-web
        # disable liveness probe when breakpoints set in debugger
        # so K8s doesn't restart unresponsive container

        livenessProbe:
          tcpSocket:
            port: 8443
          initialDelaySeconds: 180
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 8443
          initialDelaySeconds: 60
          periodSeconds: 10
        env:
        - name: WEBPROTOCOL
          value: HTTPS
        - name: WEBPORT
          value: "8443"
        - name: SDNRPROTOCOL
          value: https
        - name: SDNRHOST
          value: sdnc.onap
        - name: SDNRPORT
          value: "8443"
        - name: SSL_CERT_DIR
          value: /opt/app/osaaf/local/certs
        - name: SSL_CERTIFICATE
          value: cert.pem
        - name: SSL_CERTIFICATE_KEY
          value: key.pem
        - name: ENABLE_OAUTH
          value: "false"
        - name: ENABLE_ODLUX_RBAC
          value: "false"
        volumeMounts:
        - mountPath: /opt/app/osaaf
          name: onap-sdnc-web-aaf-config
        - mountPath: /etc/localtime
          name: localtime
          readOnly: true
        resources: {}
      serviceAccountName: onap-sdnc-web-read
      volumes:
      - name: onap-sdnc-web-aaf-config
        emptyDir:
          medium: Memory
      - name: aaf-agent-certs
        configMap:
          name: onap-cert-wrapper-certs
          defaultMode: 0700
      - name: aaf-add-config
        configMap:
          name: onap-sdnc-web-cert-initializer-add-config
          defaultMode: 0700
      - name: localtime
        hostPath:
          path: /etc/localtime
      imagePullSecrets:
      - name: "onap-docker-registry-key"
