# Source: onap/charts/policy/charts/policy-clamp-ac-k8s-ppnt/charts/serviceAccount/templates/role-binding.yaml
apiVersion: rbac.authorization.k8s.io/v1
# This cluster role binding allows anyone in the "manager" group to read secrets in any namespace.
kind: RoleBinding
metadata:
  name: onap-policy-clamp-ac-k8s-ppnt-create
  namespace: onap
subjects:
- kind: ServiceAccount
  name: onap-policy-clamp-ac-k8s-ppnt-create
roleRef:
  kind: Role
  name: onap-create
  apiGroup: rbac.authorization.k8s.io
