# Source: onap/charts/policy/charts/policy-clamp-ac-k8s-ppnt/charts/serviceAccount/templates/service-account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: onap-policy-clamp-ac-k8s-ppnt-create
  namespace: onap