# Source: onap/charts/sdnc/charts/network-name-gen/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: onap-network-name-gen
  namespace: onap
  labels:
    app: network-name-gen
    chart: network-name-gen-10.0.0
    release: onap
    heritage: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: network-name-gen
  template:
    metadata:
      labels:
        app: network-name-gen
        release: onap
    spec:
      initContainers:
      - name: network-name-gen-readiness
        command:
        - /app/ready.py
        args:
        - --job-name
        - onap-nengdb-init-config-job
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: nexus3.onap.org:10001/onap/oom/readiness:3.0.1
        imagePullPolicy: IfNotPresent
      containers:
      - name: network-name-gen
        command:
        - bash
        args:
        - '-c'
        - 'export POL_BASIC_AUTH=`echo -n $POL_BASIC_AUTH_USER:$POL_BASIC_AUTH_PASSWORD | base64`; /startService.sh'
        image: nexus3.onap.org:10001/onap/ccsdk-apps-ms-neng:1.3.0
        imagePullPolicy: IfNotPresent
        env:
        - name: SPRING_PROFILE
          value: "live"
        - name: NENG_DB_USER
          valueFrom:
            secretKeyRef:
              name: onap-neng-db-secret
              key: login
        - name: NENG_DB_PASS
          valueFrom:
            secretKeyRef:
              name: onap-neng-db-secret
              key: password
        - name: NENG_DB_URL
          value: jdbc:mysql://mariadb-galera:3306/nengdb
        - name: POL_CLIENT_AUTH
          value: "cHl0aG9uOnRlc3Q="
        - name: POL_BASIC_AUTH_USER
          valueFrom:
            secretKeyRef:
              name: onap-pol-basic-auth-secret
              key: login
        - name: POL_BASIC_AUTH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: onap-pol-basic-auth-secret
              key: password
        - name: POL_URL
          value: "https://policy-xacml-pdp:6969/policy/pdpx/v1/decision"
        - name: POL_ENV
          value: "TEST"
        - name: POL_REQ_ID
          value: "xx"
        - name: AAI_CERT_PASS
          value: "changeit"
        - name: AAI_CERT_PATH
          value: "/opt/etc/config/aai_keystore"
        - name: AAI_URI
          value: "https://aai:8443/aai/v14/"
        - name: AAI_AUTH
          value: "QUFJOkFBSQ=="
        - name: DISABLE_HOST_VERIFICATION
          value: "true"
        volumeMounts:
        - name: certs
          mountPath: /opt/etc/config/aai_keystore
          subPath: aai_keystore
          readOnly: true
        resources: null
      volumes:
      - name: certs
        secret:
          secretName: onap-aai-keystore
      imagePullSecrets:
      - name: "onap-docker-registry-key"
