# Source: onap/charts/repository-wrapper/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: onap-docker-registry-key
  namespace: onap
  labels:
    app: repository-wrapper
    chart: repository-wrapper-10.0.0
    release: onap
    heritage: Helm
data:
  .dockercfg: eyJuZXh1czMub25hcC5vcmc6MTAwMDEiOiB7InVzZXJuYW1lIjoiZG9ja2VyIiwicGFzc3dvcmQiOiJkb2NrZXIiLCJlbWFpbCI6IkAiLCJhdXRoIjoiWkc5amEyVnlPbVJ2WTJ0bGNnPT0ifX0=
type: kubernetes.io/dockercfg
