# Source: onap/charts/sdnc/charts/dgbuilder/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: onap-sdnc-dgbuilder
  namespace: onap
  labels:
    app: sdnc-dgbuilder
    chart: dgbuilder-10.0.0
    release: onap
    heritage: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sdnc-dgbuilder
  template:
    metadata:
      labels:
        app: sdnc-dgbuilder
        release: onap
    spec:
      initContainers:
      - command:
        - sh
        args:
        - -c
        - "cd /config-input && for PFILE in `ls -1 .`; do envsubst <${PFILE} >/config/${PFILE}; done"
        env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: onap-sdnc-db-secret
              key: login
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: onap-sdnc-db-secret
              key: password
        - name: HTTP_USER
          valueFrom:
            secretKeyRef:
              name: onap-sdnc-dgbuilder-http-user-creds
              key: login
        - name: HTTP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: onap-sdnc-dgbuilder-http-user-creds
              key: password
        - name: HTTP_ADMIN_USER
          valueFrom:
            secretKeyRef:
              name: onap-sdnc-dgbuilder-admin-creds
              key: login
        - name: HTTP_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: onap-sdnc-dgbuilder-admin-creds
              key: password
        - name: HTTP_NODE_USER
          valueFrom:
            secretKeyRef:
              name: onap-sdnc-dgbuilder-node-creds
              key: login
        - name: HTTP_NODE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: onap-sdnc-dgbuilder-node-creds
              key: password
        - name: REST_CONF_USER
          valueFrom:
            secretKeyRef:
              name: onap-sdnc-dgbuilder-restconf-creds
              key: login
        - name: REST_CONF_PASSWORD
          valueFrom:
            secretKeyRef:
              name: onap-sdnc-dgbuilder-restconf-creds
              key: password
        volumeMounts:
        - mountPath: /config-input
          name: config-input
        - mountPath: /config
          name: config
        image: docker.io/dibi/envsubst:1
        imagePullPolicy: IfNotPresent
        name: sdnc-dgbuilder-update-config
      - name: sdnc-dgbuilder-cert-initializer-readiness
        image: nexus3.onap.org:10001/onap/oom/readiness:3.0.1
        imagePullPolicy: IfNotPresent
        securityContext:
          runAsUser: 100
          runAsGroup: 65533
        command:
        - /app/ready.py
        args:
        - --container-name
        - aaf-locate
        - --container-name
        - aaf-cm
        - --container-name
        - aaf-service
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 3m
            memory: 20Mi
      - name: sdnc-dgbuilder-aaf-config
        image: nexus3.onap.org:10001/onap/aaf/aaf_agent:2.1.20
        imagePullPolicy: IfNotPresent
        securityContext:
          runAsUser: 0
        volumeMounts:
        - mountPath: /opt/app/osaaf
          name: onap-sdnc-dgbuilder-aaf-config
        - mountPath: /opt/app/aaf_config/cert/truststoreONAPall.jks.b64
          name: aaf-agent-certs
          subPath: truststoreONAPall.jks.b64
        - mountPath: /opt/app/aaf_config/cert/truststoreONAP.p12.b64
          name: aaf-agent-certs
          subPath: truststoreONAP.p12.b64
        - name: aaf-add-config
          mountPath: /opt/app/aaf_config/bin/retrieval_check.sh
          subPath: retrieval_check.sh
        - name: aaf-add-config
          mountPath: /opt/app/aaf_config/bin/aaf-add-config.sh
          subPath: aaf-add-config.sh
        command:
        - sh
        - -c
        - |
          /opt/app/aaf_config/bin/agent.sh
          . /opt/app/aaf_config/bin/retrieval_check.sh
          /opt/app/aaf_config/bin/aaf-add-config.sh
        env:
        - name: APP_FQI
          value: "sdnc@sdnc.onap.org"
        - name: aaf_locate_url
          value: "https://aaf-locate.onap:8095"
        - name: aaf_locator_container_ns
          value: "onap"
        - name: aaf_locator_container
          value: "oom"
        - name: aaf_locator_fqdn
          value: "sdnc"
        - name: aaf_locator_app_ns
          value: "org.osaaf.aaf"
        - name: DEPLOY_FQI
          valueFrom:
            secretKeyRef:
              name: onap-sdnc-dgbuilder-cert-initializer-deployer-creds
              key: login
        - name: DEPLOY_PASSWORD
          valueFrom:
            secretKeyRef:
              name: onap-sdnc-dgbuilder-cert-initializer-deployer-creds
              key: password
              #Note: want to put this on Nodes, eventually
        - name: cadi_longitude
          value: "-72.0"
        - name: cadi_latitude
          value: "38.0"
          #Hello specific.  Clients don't don't need this, unless Registering with AAF Locator
        - name: aaf_locator_public_fqdn
          value: "dgbuilder.onap.org"
      - command:
        - /app/ready.py
        args:
        - --container-name
        - mariadb-galera
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: nexus3.onap.org:10001/onap/oom/readiness:3.0.1
        imagePullPolicy: IfNotPresent
        name: sdnc-dgbuilder-readiness
      containers:
      - name: sdnc-dgbuilder
        image: nexus3.onap.org:10001/onap/ccsdk-dgbuilder-image:1.3.1
        imagePullPolicy: IfNotPresent
        command: ["/bin/bash"]
        args: ["-c", "cd /opt/onap/ccsdk/dgbuilder/ &&  cp /opt/app/osaaf/local/node-*.pem certs && ./start.sh sdnc1.0 && wait"]
        ports:
        - containerPort: 3100
        readinessProbe:
          tcpSocket:
            port: 3100
          initialDelaySeconds: 10
          periodSeconds: 10
        env:
        - name: SDNC_CONFIG_DIR
          value: /opt/onap/sdnc/data/properties
        volumeMounts:
        - mountPath: /opt/app/osaaf
          name: onap-sdnc-dgbuilder-aaf-config
        - mountPath: /etc/localtime
          name: localtime
          readOnly: true
        - name: config
          mountPath: /opt/app/application.properties
          subPath: application.properties
        - name: config
          mountPath: /opt/onap/ccsdk/dgbuilder/releases/sdnc1.0/conf/svclogic.properties
          subPath: svclogic.properties
        - name: config
          mountPath: /opt/onap/ccsdk/dgbuilder/svclogic/svclogic.properties
          subPath: svclogic.properties
        - name: config
          mountPath: /opt/onap/ccsdk/dgbuilder/releases/sdnc1.0/customSettings.js
          subPath: customSettings.js
        resources: {}
      serviceAccountName: onap-sdnc-dgbuilder-read
      volumes:
      - name: onap-sdnc-dgbuilder-aaf-config
        emptyDir:
          medium: Memory
      - name: aaf-agent-certs
        configMap:
          name: onap-cert-wrapper-certs
          defaultMode: 0700
      - name: aaf-add-config
        configMap:
          name: onap-sdnc-dgbuilder-cert-initializer-add-config
          defaultMode: 0700
      - name: localtime
        hostPath:
          path: /etc/localtime
      - name: config-input
        configMap:
          name: onap-sdnc-dgbuilder-config
      - name: config
        emptyDir:
          medium: Memory
      imagePullSecrets:
      - name: "onap-docker-registry-key"
