# Source: onap/charts/sdnc/charts/dmaap-listener/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: onap-sdnc-dmaap-listener
  namespace: onap
  labels:
    app: sdnc-dmaap-listener
    chart: dmaap-listener-10.0.0
    release: onap
    heritage: Helm
data:
  aai.properties: |-
    TransportType=HTTPAUTH
    Latitude =50.000000
    Longitude =-100.000000
    Version =1.0
    ServiceName =dmaap-v1.dev.dmaap.dt.saat.acsi.openecomp.org/events
    Environment =TEST
    Partner = BOT_R
    routeOffer=MR1
    SubContextPath =/
    Protocol =http
    MethodType =GET
    username =admin
    password =admin
    contenttype =application/json
    authKey=fxoW4jZrO7mdLWWa:f4KxkoBtToyoEG7suMoV8KhnkwM=
    authDate=2016-02-18T13:57:37-0800
    host=message-router.onap:3904
    topic=AAI-EVENT
    group=jmsgrp
    id=sdnc2
    timeout=15000
    limit=1000
    filter=
    AFT_DME2_EXCHANGE_REQUEST_HANDLERS=com.att.nsa.test.PreferredRouteRequestHandler
    AFT_DME2_EXCHANGE_REPLY_HANDLERS=com.att.nsa.test.PreferredRouteReplyHandler
    AFT_DME2_REQ_TRACE_ON=true
    AFT_ENVIRONMENT=AFTUAT
    AFT_DME2_EP_CONN_TIMEOUT=15000
    AFT_DME2_ROUNDTRIP_TIMEOUT_MS=240000
    AFT_DME2_EP_READ_TIMEOUT_MS=50000
    sessionstickinessrequired=NO
    DME2preferredRouterFilePath=/opt/onap/sdnc/data/properties/dmaap-listener.preferredRoute.txt
    sdnc.odl.user=${ODL_USER}
    sdnc.odl.password=${ODL_PASSWORD}
    sdnc.odl.url-base=http://sdnc-oam.onap:8282/restconf/operations
  dblib.properties: |2

    org.onap.ccsdk.sli.dbtype=jdbc
    org.onap.ccsdk.sli.jdbc.hosts=sdnctldb01
    org.onap.ccsdk.sli.jdbc.url=jdbc:mysql://mariadb-galera:3306/sdnctl
    org.onap.ccsdk.sli.jdbc.driver=org.mariadb.jdbc.Driver
    org.onap.ccsdk.sli.jdbc.database=sdnctl
    org.onap.ccsdk.sli.jdbc.user=${SDNC_DB_USER}
    org.onap.ccsdk.sli.jdbc.password=${SDNC_DB_PASSWORD}
    org.onap.ccsdk.sli.jdbc.connection.name=sdnctldb01
    org.onap.ccsdk.sli.jdbc.connection.timeout=50
    org.onap.ccsdk.sli.jdbc.request.timeout=100
    org.onap.ccsdk.sli.jdbc.limit.init=10
    org.onap.ccsdk.sli.jdbc.limit.min=10
    org.onap.ccsdk.sli.jdbc.limit.max=20
    org.onap.dblib.connection.recovery=false
  dhcpalert.properties: |
    TransportType=HTTPAUTH
    Latitude =50.000000
    Longitude =-100.000000
    Version =1.0
    ServiceName =message-router.onap:3904/events
    Environment =TEST
    Partner = BOT_R
    routeOffer=MR1
    SubContextPath =/
    Protocol =http
    MethodType =GET
    username =admin
    password =admin
    contenttype =application/json
    authKey=fxoW4jZrO7mdLWWa:f4KxkoBtToyoEG7suMoV8KhnkwM=
    authDate=2016-02-18T13:57:37-0800
    host=message-router.onap:3904
    topic=VCPE-DHCP-EVENT
    group=jmsgrp
    id=sdnc1
    timeout=15000
    limit=1000
    filter=
    AFT_DME2_EXCHANGE_REQUEST_HANDLERS=com.att.nsa.test.PreferredRouteRequestHandler
    AFT_DME2_EXCHANGE_REPLY_HANDLERS=com.att.nsa.test.PreferredRouteReplyHandler
    AFT_DME2_REQ_TRACE_ON=true
    AFT_ENVIRONMENT=AFTUAT
    AFT_DME2_EP_CONN_TIMEOUT=15000
    AFT_DME2_ROUNDTRIP_TIMEOUT_MS=240000
    AFT_DME2_EP_READ_TIMEOUT_MS=50000
    sessionstickinessrequired=NO
    DME2preferredRouterFilePath=/opt/onap/sdnc/data/properties/dmaap-listener.preferredRoute.txt
    sdnc.odl.user=${ODL_USER}
    sdnc.odl.password=${ODL_PASSWORD}
    sdnc.odl.url-base=http://sdnc-oam.onap:8282/restconf/operations
  dmaap-consumer-CMNotify.properties: |
    TransportType=HTTPNOAUTH
    Latitude =50.000000
    Longitude =-100.000000
    Version =1.0
    ServiceName=message-router.onap:3904/events
    Environment =TEST
    Partner =
    routeOffer=MR1
    SubContextPath =/
    Protocol =http
    MethodType =GET
    username =UNUSED
    password =UNUSED
    contenttype =application/json
    authKey=UNUSED
    authDate=UNUSED
    host=message-router.onap:3904
    topic=CM-NOTIFICATION
    group=users
    id=sdnc1
    timeout=15000
    limit=1000
    filter=
    AFT_DME2_EXCHANGE_REQUEST_HANDLERS=com.att.nsa.test.PreferredRouteRequestHandler
    AFT_DME2_EXCHANGE_REPLY_HANDLERS=com.att.nsa.test.PreferredRouteReplyHandler
    AFT_DME2_REQ_TRACE_ON=true
    AFT_ENVIRONMENT=AFTUAT
    AFT_DME2_EP_CONN_TIMEOUT=15000
    AFT_DME2_ROUNDTRIP_TIMEOUT_MS=240000
    AFT_DME2_EP_READ_TIMEOUT_MS=50000
    sessionstickinessrequired=NO
    DME2preferredRouterFilePath=/opt/onap/sdnc/data/properties/dmaap-listener.preferredRoute.txt
    sdnc.odl.user=${ODL_USER}
    sdnc.odl.password=${ODL_PASSWORD}
    sdnc.odl.url-base=http://sdnc-oam.onap:8282/restconf/operations
  dmaap-consumer-RANSlice.properties: |
    TransportType=HTTPNOAUTH
    Latitude =50.000000
    Longitude =-100.000000
    Version =1.0
    ServiceName=message-router.onap:3904/events
    Environment =TEST
    Partner =
    routeOffer=MR1
    SubContextPath =/
    Protocol =http
    MethodType =GET
    username =UNUSED
    password =UNUSED
    contenttype =application/json
    authKey=UNUSED
    authDate=UNUSED
    host=message-router.onap:3904
    topic=RAN-Slice-Mgmt
    group=users
    id=sdnc1
    timeout=15000
    limit=1000
    filter=
    AFT_DME2_EXCHANGE_REQUEST_HANDLERS=com.att.nsa.test.PreferredRouteRequestHandler
    AFT_DME2_EXCHANGE_REPLY_HANDLERS=com.att.nsa.test.PreferredRouteReplyHandler
    AFT_DME2_REQ_TRACE_ON=true
    AFT_ENVIRONMENT=AFTUAT
    AFT_DME2_EP_CONN_TIMEOUT=15000
    AFT_DME2_ROUNDTRIP_TIMEOUT_MS=240000
    AFT_DME2_EP_READ_TIMEOUT_MS=50000
    sessionstickinessrequired=NO
    DME2preferredRouterFilePath=/opt/onap/sdnc/data/properties/dmaap-listener.preferredRoute.txt
    sdnc.odl.user=${ODL_USER}
    sdnc.odl.password=${ODL_PASSWORD}
    sdnc.odl.url-base=http://sdnc-oam.onap:8282/restconf/operations
  dmaap-consumer-a1Adapter-policy.properties: |
    TransportType=HTTPNOAUTH
    Latitude =50.000000
    Longitude =-100.000000
    Version =1.0
    ServiceName=message-router.onap:3904/events
    Environment =TEST
    Partner =
    routeOffer=MR1
    SubContextPath =/
    Protocol =http
    MethodType =GET
    username =UNUSED
    password =UNUSED
    contenttype =application/json
    authKey=UNUSED
    authDate=UNUSED
    host=message-router.onap:3904
    topic=A1-P
    group=users
    id=sdnc1
    timeout=15000
    limit=1000
    filter=
    AFT_DME2_EXCHANGE_REQUEST_HANDLERS=com.att.nsa.test.PreferredRouteRequestHandler
    AFT_DME2_EXCHANGE_REPLY_HANDLERS=com.att.nsa.test.PreferredRouteReplyHandler
    AFT_DME2_REQ_TRACE_ON=true
    AFT_ENVIRONMENT=AFTUAT
    AFT_DME2_EP_CONN_TIMEOUT=15000
    AFT_DME2_ROUNDTRIP_TIMEOUT_MS=240000
    AFT_DME2_EP_READ_TIMEOUT_MS=50000
    sessionstickinessrequired=NO
    DME2preferredRouterFilePath=/opt/onap/sdnc/data/properties/dmaap-listener.preferredRoute.txt
    sdnc.odl.user=${ODL_USER}
    sdnc.odl.password=${ODL_PASSWORD}
    sdnc.odl.url-base=http://sdnc-oam.onap:8282/restconf/operations
  dmaap-consumer-oofpcipoc.properties: |
    TransportType=HTTPNOAUTH
    Latitude =50.000000
    Longitude =-100.000000
    Version =1.0
    ServiceName=message-router.onap:3904/events
    Environment =TEST
    Partner =
    routeOffer=MR1
    SubContextPath =/
    Protocol =http
    MethodType =GET
    username =UNUSED
    password =UNUSED
    contenttype =application/json
    authKey=UNUSED
    authDate=UNUSED
    host=message-router.onap:3904
    topic=SDNR-CL
    group=users
    id=sdnc1
    timeout=15000
    limit=1000
    filter=
    AFT_DME2_EXCHANGE_REQUEST_HANDLERS=com.att.nsa.test.PreferredRouteRequestHandler
    AFT_DME2_EXCHANGE_REPLY_HANDLERS=com.att.nsa.test.PreferredRouteReplyHandler
    AFT_DME2_REQ_TRACE_ON=true
    AFT_ENVIRONMENT=AFTUAT
    AFT_DME2_EP_CONN_TIMEOUT=15000
    AFT_DME2_ROUNDTRIP_TIMEOUT_MS=240000
    AFT_DME2_EP_READ_TIMEOUT_MS=50000
    sessionstickinessrequired=NO
    DME2preferredRouterFilePath=/opt/onap/sdnc/data/properties/dmaap-listener.preferredRoute.txt
    sdnc.odl.user=${ODL_USER}
    sdnc.odl.password=${ODL_PASSWORD}
    sdnc.odl.url-base=http://sdnc-oam.onap:8282/restconf/operations
  lcm.properties: |-
    TransportType=HTTPAUTH
    Latitude =50.000000
    Longitude =-100.000000
    Version =1.0
    ServiceName =message-router.onap:3904/events
    Environment =TEST
    Partner = BOT_R
    routeOffer=MR1
    SubContextPath =/
    Protocol =http
    MethodType =GET
    username =admin
    password =admin
    contenttype =application/json
    authKey=fxoW4jZrO7mdLWWa:f4KxkoBtToyoEG7suMoV8KhnkwM=
    authDate=2016-02-18T13:57:37-0800
    host=message-router.onap:3904
    topic=SDNC-LCM-READ
    group=jmsgrp
    id=sdnc2
    timeout=15000
    limit=1000
    filter=
    AFT_DME2_EXCHANGE_REQUEST_HANDLERS=com.att.nsa.test.PreferredRouteRequestHandler
    AFT_DME2_EXCHANGE_REPLY_HANDLERS=com.att.nsa.test.PreferredRouteReplyHandler
    AFT_DME2_REQ_TRACE_ON=true
    AFT_ENVIRONMENT=AFTUAT
    AFT_DME2_EP_CONN_TIMEOUT=15000
    AFT_DME2_ROUNDTRIP_TIMEOUT_MS=240000
    AFT_DME2_EP_READ_TIMEOUT_MS=50000
    sessionstickinessrequired=NO
    DME2preferredRouterFilePath=/opt/onap/sdnc/data/properties/dmaap-listener.preferredRoute.txt
    sdnc.odl.user=${ODL_USER}
    sdnc.odl.password=${ODL_PASSWORD}
    sdnc.odl.url-base=http://sdnc-oam.onap:8282/restconf/operations
