# Source: onap/charts/aaf/charts/aaf-sms/charts/aaf-sms-vault/templates/pv.yaml
kind: PersistentVolume
apiVersion: v1
metadata:
  name: onap-aaf-sms-vault-data-0
  #namespace: onap
  labels:
    app: aaf-sms-vault
    chart: "aaf-sms-vault-10.0.0"
    release: "onap"
    heritage: "Helm"
    name: onap-aaf-sms-vault
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "onap-aaf-sms-vault-data"
  hostPath:
    path: /dockerdata-nfs/deployment-1670599359/onap/sms/consul/data-0
