# Source: onap/charts/dmaap/charts/message-router/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: onap-message-router-secret
  namespace: onap
  labels:
    app: message-router
    chart: message-router-10.0.0
    release: onap
    heritage: Helm
data: {}
type: Opaque
