# Source: onap/charts/policy/charts/policy-clamp-be/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: onap-policy-clamp-be-sdc-creds
  namespace: onap
  labels:
    app: policy-clamp-be
    chart: policy-clamp-be-10.0.0
    release: onap
    heritage: Helm
type: Opaque
stringData:
  password: "Kp8bJ4SXszM0WXlhak3eHlcse2gAw84vaoGGmJvUy2U"
