# Source: onap/charts/policy/charts/policy-clamp-be/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: policy-clamp-be
  namespace: onap
  labels:
    app: policy-clamp-be
    chart: policy-clamp-be-10.0.0
    release: onap
    heritage: Helm
spec:
  type: ClusterIP
  ports:
    - port: 8443
      targetPort: 8443
      name: policy-clamp-be
  selector:
    app: policy-clamp-be
    release: onap
