# Source: onap/charts/dmaap/charts/dmaap-bc/charts/postgres/templates/pv-primary.yaml
kind: PersistentVolume
apiVersion: v1
metadata:
  name: onap-dbc-pg-primary
  #namespace: onap
  labels:
    app: onap-dbc-pg
    chart: "postgres-10.0.0"
    release: "onap"
    heritage: "Helm"
    name: onap-dbc-pg
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: "onap-dbc-pg-primary"
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /dockerdata-nfs/deployment-1670599359/onap/dbc/data/primary
