# Source: onap/charts/dmaap/charts/dmaap-bc/charts/postgres/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: onap-dbc-pg-primary-password
  namespace: onap
  labels:
    app: dbc-pg
    chart: postgres-10.0.0
    release: onap
    heritage: Helm
type: Opaque
stringData:
  password: "WMZ1sAJ0"
