# Source: onap/charts/dmaap/charts/dmaap-bc/charts/postgres/templates/service-replica.yaml
apiVersion: v1
kind: Service
metadata:
  name: dbc-pg-replica
  namespace: onap
  labels:
    app: dbc-pg-replica
    chart: postgres-10.0.0
    release: onap
    heritage: Helm
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      name: tcp-postgres
  selector:
    name: "dbc-pg-replica"
    release: onap
