# Source: onap/charts/sdnc/charts/elasticsearch/templates/discovery-svc.yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: sdnrdb-discovery
  namespace: onap
  labels:
    app.kubernetes.io/name: sdnrdb
    helm.sh/chart: elasticsearch-10.0.0
    app.kubernetes.io/instance: onap
    app.kubernetes.io/managed-by: Helm
spec:
  clusterIP: None
  ports:
  - port: 9300
    targetPort: http-transport
    protocol: TCP
    name: http-transport
  ipFamilyPolicy: PreferDualStack
  publishNotReadyAddresses: true
  type: ClusterIP
  selector:
    app.kubernetes.io/instance: onap
    discovery: sdnrdb-cluster
  sessionAffinity: None
