# Source: onap/charts/policy/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: onap-policy-db-root-password
  namespace: onap
  labels:
    app: policy
    chart: policy-10.0.0
    release: onap
    heritage: Helm
type: Opaque
stringData:
  password: "TagaXiko6.Faja"
---
# Source: onap/charts/policy/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: onap-policy-db-secret
  namespace: onap
  labels:
    app: policy
    chart: policy-10.0.0
    release: onap
    heritage: Helm
type: Opaque
stringData:
  login: "policy_user"
  password: "GiwiCeneTugo8#"
---
# Source: onap/charts/policy/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: onap-policy-pg-root-pass
  namespace: onap
  labels:
    app: policy
    chart: policy-10.0.0
    release: onap
    heritage: Helm
type: Opaque
stringData:
  password: "Fuxi8-BuhiGinq"
---
# Source: onap/charts/policy/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: onap-policy-pg-user-creds
  namespace: onap
  labels:
    app: policy
    chart: policy-10.0.0
    release: onap
    heritage: Helm
type: Opaque
stringData:
  login: "policy_user"
  password: "Saxj1-BusaKofu"
---
# Source: onap/charts/policy/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: onap-policy-api-user-creds
  namespace: onap
  labels:
    app: policy
    chart: policy-10.0.0
    release: onap
    heritage: Helm
type: Opaque
stringData:
  login: "policyadmin"
  password: "zb!XztG34"
---
# Source: onap/charts/policy/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: onap-policy-app-user-creds
  namespace: onap
  labels:
    app: policy
    chart: policy-10.0.0
    release: onap
    heritage: Helm
type: Opaque
stringData:
  login: "runtimeUser"
  password: "ZiboTipdZeyt9]"
---
# Source: onap/charts/policy/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: onap-policy-pap-user-creds
  namespace: onap
  labels:
    app: policy
    chart: policy-10.0.0
    release: onap
    heritage: Helm
type: Opaque
stringData:
  login: "policyadmin"
  password: "zb!XztG34"
