# Source: onap/charts/a1policymanagement/templates/envsubst-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: onap-a1policymanagement
  namespace: onap
  labels:
    app.kubernetes.io/name: a1policymanagement
    helm.sh/chart: a1policymanagement-10.0.0
    app.kubernetes.io/instance: onap
    app.kubernetes.io/managed-by: Helm
  name: onap-a1policymanagement-envsubst-scripts
data:
  daemon.sh: |
    #!/bin/sh


    terminate() {
      echo "$(date) | INFO | Terminating child processes"
      pids="$(jobs -p)"
      if [ "$pids" != "" ]; then
        kill -TERM $pids >/dev/null 2>/dev/null
      fi
      wait
    }

    trap terminate TERM
    echo "$(date) | INFO | Started monitoring /config-input/ directory"
    inotifyd /tmp/scripts/update_files /config-input/ &
    wait
  update_files: |
    #!/bin/sh


    if [ "$1" == "y" ] && [ "$3" == "..data" ]; then
      echo "$(date) | INFO | Configmap has been reloaded"
      cd /config-input
      for file in $(ls -1); do
        if [ "$file" -nt "/config/$file" ]; then
          echo "$(date) | INFO | Templating /config/$file"
          envsubst <$file >/config/$file
        fi
      done
    fi
