# Source: onap/charts/aaf/charts/aaf-sms/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: onap-aaf-sms-aaf-creds
  namespace: onap
  labels:
    app: aaf-sms
    chart: aaf-sms-10.0.0
    release: onap
    heritage: Helm
type: Opaque
stringData:
  login: "aaf_admin@people.osaaf.org"
  password: "demo123456!"
---
# Source: onap/charts/aaf/charts/aaf-sms/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: onap-aaf-sms-aai-creds
  namespace: onap
  labels:
    app: aaf-sms
    chart: aaf-sms-10.0.0
    release: onap
    heritage: Helm
type: Opaque
stringData:
  login: "oof@oof.onap.org"
  password: "demo123456!"
---
# Source: onap/charts/aaf/charts/aaf-sms/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: onap-aaf-sms-conductor-creds
  namespace: onap
  labels:
    app: aaf-sms
    chart: aaf-sms-10.0.0
    release: onap
    heritage: Helm
type: Opaque
stringData:
  login: "admin1"
  password: "plan.15"
---
# Source: onap/charts/aaf/charts/aaf-sms/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: onap-aaf-sms-config-db-creds
  namespace: onap
  labels:
    app: aaf-sms
    chart: aaf-sms-10.0.0
    release: onap
    heritage: Helm
type: Opaque
stringData:
  login: "osdf"
  password: "passwd"
---
# Source: onap/charts/aaf/charts/aaf-sms/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: onap-aaf-sms-music-creds
  namespace: onap
  labels:
    app: aaf-sms
    chart: aaf-sms-10.0.0
    release: onap
    heritage: Helm
type: Opaque
stringData:
  login: "conductor"
  password: "c0nduct0r"
---
# Source: onap/charts/aaf/charts/aaf-sms/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: onap-aaf-sms-osdf-cm-scheduler-creds
  namespace: onap
  labels:
    app: aaf-sms
    chart: aaf-sms-10.0.0
    release: onap
    heritage: Helm
type: Opaque
stringData:
  login: "test1"
  password: "testpwd1"
---
# Source: onap/charts/aaf/charts/aaf-sms/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: onap-aaf-sms-osdf-opt-engine-creds
  namespace: onap
  labels:
    app: aaf-sms
    chart: aaf-sms-10.0.0
    release: onap
    heritage: Helm
type: Opaque
stringData:
  login: "opt_test"
  password: "opt_testpwd"
---
# Source: onap/charts/aaf/charts/aaf-sms/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: onap-aaf-sms-osdf-pci-opt-creds
  namespace: onap
  labels:
    app: aaf-sms
    chart: aaf-sms-10.0.0
    release: onap
    heritage: Helm
type: Opaque
stringData:
  login: "pci_test"
  password: "pci_testpwd"
---
# Source: onap/charts/aaf/charts/aaf-sms/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: onap-aaf-sms-osdf-placement-creds
  namespace: onap
  labels:
    app: aaf-sms
    chart: aaf-sms-10.0.0
    release: onap
    heritage: Helm
type: Opaque
stringData:
  login: "test"
  password: "testpwd"
---
# Source: onap/charts/aaf/charts/aaf-sms/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: onap-aaf-sms-osdf-placement-so-creds
  namespace: onap
  labels:
    app: aaf-sms
    chart: aaf-sms-10.0.0
    release: onap
    heritage: Helm
type: Opaque
stringData:
  login: "so_test"
  password: "so_testpwd"
---
# Source: onap/charts/aaf/charts/aaf-sms/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: onap-aaf-sms-osdf-placement-vfc-creds
  namespace: onap
  labels:
    app: aaf-sms
    chart: aaf-sms-10.0.0
    release: onap
    heritage: Helm
type: Opaque
stringData:
  login: "vfc_test"
  password: "vfc_testpwd"
---
# Source: onap/charts/aaf/charts/aaf-sms/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: onap-aaf-sms-policy-cli-creds
  namespace: onap
  labels:
    app: aaf-sms
    chart: aaf-sms-10.0.0
    release: onap
    heritage: Helm
type: Opaque
stringData:
  login: "healthcheck"
  password: "zb!XztG34"
---
# Source: onap/charts/aaf/charts/aaf-sms/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: onap-aaf-sms-policy-plat-creds
  namespace: onap
  labels:
    app: aaf-sms
    chart: aaf-sms-10.0.0
    release: onap
    heritage: Helm
type: Opaque
stringData:
  login: "healthcheck"
  password: "zb!XztG34"
---
# Source: onap/charts/aaf/charts/aaf-sms/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: onap-aaf-sms-sdc-creds
  namespace: onap
  labels:
    app: aaf-sms
    chart: aaf-sms-10.0.0
    release: onap
    heritage: Helm
type: Opaque
stringData:
  login: "aai"
  password: "Kp8bJ4SXszM0WXlhak3eHlcse2gAw84vaoGGmJvUy2U"
---
# Source: onap/charts/aaf/charts/aaf-sms/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: onap-aaf-sms-sdnc-creds
  namespace: onap
  labels:
    app: aaf-sms
    chart: aaf-sms-10.0.0
    release: onap
    heritage: Helm
type: Opaque
stringData:
  login: "admin"
  password: "Kp8bJ4SXszM0WXlhak3eHlcse2gAw84vaoGGmJvUy2U"
---
# Source: onap/charts/aaf/charts/aaf-sms/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: onap-aaf-sms-so-creds
  namespace: onap
  labels:
    app: aaf-sms
    chart: aaf-sms-10.0.0
    release: onap
    heritage: Helm
type: Opaque
stringData:
  login: "apihBpmn"
  password: "password1$"
---
# Source: onap/charts/aaf/charts/aaf-sms/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: onap-aaf-sms-int-certs
  namespace: onap
  labels:
    app: aaf-sms
    chart: aaf-sms-10.0.0
    release: onap
    heritage: Helm
data:
  intermediate_root_ca.pem: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVkVENDQWwyZ0F3SUJBZ0lCQnpBTkJna3Foa2lHOXcwQkFRc0ZBREFzTVE0d0RBWURWUVFMREFWUFUwRkIKUmpFTk1Bc0dBMVVFQ2d3RVQwNUJVREVMTUFrR0ExVUVCaE1DVlZNd0hoY05NVGd3T0RFM01UZzFNVE0zV2hjTgpNak13T0RFM01UZzFNVE0zV2pCSE1Rc3dDUVlEVlFRR0V3SlZVekVOTUFzR0ExVUVDZ3dFVDA1QlVERU9NQXdHCkExVUVDd3dGVDFOQlFVWXhHVEFYQmdOVkJBTU1FR2x1ZEdWeWJXVmthV0YwWlVOQlh6a3dnZ0VpTUEwR0NTcUcKU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRQ3YwSEhVa2JhM3VOdE5JM2pQS2ltVWNkNlJOd21oU0NKTApuZU1XcG5qcXA1L0ErSENLeU5zRWFUNHkxNzdoTkxtQ20vYU1tMXUySklmaWtjKzh3RXFMQ1NCQlB6K1AwaCtkCm8rc1o3VSs0b2VRaXpkWVlwRWR6SEoyU2llSEhhOHZ0dTgwclUzbk8yTkVJa3VZQzIwSGNLU0V0bDhmRktzazMKbnFsaFkrdEdmWUpQVFhjRE9RQU80MEJUY2dhdDNDM3VJSkhrV0pKNFJpdnVuRTRMRXVSdjlReUtnQXc3cmtKVgp2K2Y3Z3VxcFpsWHk2ZHpBa3VVN1hVTFdjZ281NU1rWmxzc29pRXJNdkVaSmFkNWFXS3ZSWTNnN3FVamFRNndPCjE1d09BVW9SQlc5NmVlWlpieXRnbjhreWJjQnkrK1VlNDlnUHRnbTFNRi9LbEFzcDBNRDVBZ01CQUFHamdZWXcKZ1lNd0hRWURWUjBPQkJZRUZJSDNtVnNRdWNpTTN2TlNYdXBPYWFCRFBxemRNQjhHQTFVZEl3UVlNQmFBRkZOVgpNL0pMNjlCUnNjRjRtc0VvTVh2djZ1MUpNQklHQTFVZEV3RUIvd1FJTUFZQkFmOENBUUV3RGdZRFZSMFBBUUgvCkJBUURBZ0dHTUIwR0ExVWRKUVFXTUJRR0NDc0dBUVVGQndNQkJnZ3JCZ0VGQlFjREFqQU5CZ2txaGtpRzl3MEIKQVFzRkFBT0NBZ0VBRHhOeW1pQ05yMmUzN2lMUmVvYXhLbVp2d294MGNUaU5BYWo3aWFmUnptd0lvWTNWWE84UQppeDVJWWNwNEZhUTdmVjFqeXAvQW1hU255SGY2T3NsMHN4OFB4c1FrTzdBTHR0eEtVcmpmYnZOU1ZVQTJDL3ZsCnU1bTdVVkpMSVV0RkRaQldhbnpVU21rVHNZTEhwaUFORlFLZDJjL2NVMXFYY3l6Z0pWRkVGVnl5SE5rRjdJcysKK3BqRzlNMWh3UUhPb1RuRXVVMDEzUDdYMW1IZWsrUlhFZmhKV3dlN1VzWm5CS1phWktiUVp1N2hFdHFLV1lwLwpRc0hnbmpvTFlYc2gwV0Q1cnovbUJ4ZFRkRExHcEZxV0R6RHFiOHJzWW5xQnpvb3d2c2FzVjhYOE9Ta292MEh0CjhZa2EwY2tGSDl5ZjhqMUN3bWJsNnR0dW9uT2hreTNOL2d3TEVvenVoeTdUUGNaR1Z5emV2Rjcwa1h5N2cxQ1gKa3BGR0p5RUhYb3BybE5pOEZSNEkrTkZ6YkRlNmEyY0ZvdzFKTjE5QUo5WjVSazVtN00wbVFQYVE0UmNpa2pCMwphb0xzQVNDSlRtMU9wT0ZIZnhFS2lCVzRMc3AzVWM1L1JiOVpOYmZMcndxV1pSTTdidVcxZTNla0xxbnRnYmt5CnVLS0lTSHFWSnV3L3ZYSGwxak5pYkVvOStKdVE4OFZOdUFjbTdXcEdVb2dlQ2EyaUFsUFRja1BaZWkrTXdaOHcKdHB2eFR5WWxaRUM4RFd6WTFWQzI5K1cyTjVjdmgwMWUyRTNRbDA4VzF6TDYzZHFyZ2RFWjNWV2p6b29ZaTRlcApCbU1YVHZvdVcrRmx5dmN3LzBvVGNmTjBiaURJdDBtQ2taNUNRVmpmR0w5RFRPWXRlUjVodytrPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
