# Source: onap/charts/aaf/charts/aaf-cass/templates/pv.yaml
kind: PersistentVolume
apiVersion: v1
metadata:
  name: onap-aaf-cass-data
  namespace: onap
  labels:
    app.kubernetes.io/name: aaf-cass
    helm.sh/chart: aaf-cass-10.0.0
    app.kubernetes.io/instance: onap
    app.kubernetes.io/managed-by: Helm
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "onap-aaf-cass-data"
  hostPath:
    path: /dockerdata-nfs/deployment-1670599359/onap/cass
