# Source: strimzi-kafka-operator/templates/010-ServiceAccount-strimzi-cluster-operator.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: strimzi-cluster-operator
  labels:
    app: strimzi
    chart: strimzi-kafka-operator-0.28.0
    component: service-account
    release: strimzi-kafka-operator
    heritage: Helm
  namespace: strimzi-system
