# Source: onap/charts/dmaap/charts/dmaap-dr-prov/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: onap-dmaap-dr-db-user-credentials
  namespace: onap
  labels:
    app: dmaap-dr-prov
    chart: dmaap-dr-prov-10.0.0
    release: onap
    heritage: Helm
type: Opaque
stringData:
  login: "datarouter"
  password: "Poxu5=YawvCuyy"
