# Source: onap/charts/dmaap/charts/dmaap-dr-prov/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: dmaap-dr-prov
  namespace: onap
  labels:
    app: dmaap-dr-prov
    chart: dmaap-dr-prov-10.0.0
    release: onap
    heritage: Helm
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
    msb.onap.org/service-info: '[ { "serviceName": "dmaap-dr-prov", "version": "v1", "url": "/", "protocol": "REST", "port": "443", "visualRange":"1" } ]'
spec:
  type: NodePort
  ports:
    - port: 443
      targetPort: 8443
      nodePort: 30269
      name: dr-prov-port2
  selector:
    app: dmaap-dr-prov
    release: onap
