# Source: onap/charts/policy/charts/policy-apex-pdp/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: policy-apex-pdp
  namespace: onap
  labels:
    app: policy-apex-pdp
    chart: policy-apex-pdp-10.0.0
    release: onap
    heritage: Helm
spec:
  type: ClusterIP
  ports:
    - port: 6969
      targetPort: 6969
      name: policy-apex-pdp
  selector:
    app: policy-apex-pdp
    release: onap
  sessionAffinity: None
