# Source: onap/charts/policy/charts/policy-clamp-runtime-acm/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: onap-policy-clamp-runtime-acm-configmap
  namespace: onap
  labels:
    app: policy-clamp-runtime-acm
    chart: policy-clamp-runtime-acm-10.0.0
    release: onap
    heritage: Helm
data:
  acRuntimeParameters.yaml: |
    #  ============LICENSE_START=======================================================
    #   Copyright (C) 2021-2022 Nordix Foundation.
    #  ================================================================================
    #  Licensed under the Apache License, Version 2.0 (the "License");
    #  you may not use this file except in compliance with the License.
    #  You may obtain a copy of the License at
    #
    #       http://www.apache.org/licenses/LICENSE-2.0
    #
    #  Unless required by applicable law or agreed to in writing, software
    #  distributed under the License is distributed on an "AS IS" BASIS,
    #  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    #  See the License for the specific language governing permissions and
    #  limitations under the License.
    #
    #  SPDX-License-Identifier: Apache-2.0
    #  ============LICENSE_END=========================================================

    spring:
      security:
        user:
          name: ${RUNTIME_USER}
          password: ${RUNTIME_PASSWORD}
      http:
        converters:
          preferred-json-mapper: gson
      datasource:
        url: jdbc:mariadb://policy-mariadb:3306/clampacm
        driverClassName: org.mariadb.jdbc.Driver
        username: ${SQL_USER}
        password: ${SQL_PASSWORD}
        hikari:
          connectionTimeout: 30000
          idleTimeout: 600000
          maxLifetime: 1800000
          maximumPoolSize: 10
      jpa:
        hibernate:
          ddl-auto: update
          naming:
            physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
            implicit-strategy: org.onap.policy.common.spring.utils.CustomImplicitNamingStrategy
        properties:
          hibernate:
            dialect: org.hibernate.dialect.MariaDB103Dialect
            format_sql: true

    security:
      enable-csrf: false

    server:
      port: 6969
      servlet:
        context-path: /onap/policy/clamp/acm
      error:
        path: /error


    runtime:
      participantParameters:
        heartBeatMs: 120000
        maxMessageAgeMs: 600000
        maxStatusWaitMs: 100000
        updateParameters:
          maxRetryCount: 3
          maxWaitMs: 100000
      topicParameterGroup:
        topicSources:
          -
            topic: POLICY-ACRUNTIME-PARTICIPANT
            servers:
              - ${topicServer:message-router}
            topicCommInfrastructure: dmaap
            useHttps: true
            fetchTimeout: 15000
        topicSinks:
          -
            topic: POLICY-ACRUNTIME-PARTICIPANT
            servers:
              - ${topicServer:message-router}
            topicCommInfrastructure: dmaap
            useHttps: true

    management:
      endpoints:
        web:
          exposure:
            include: health, metrics, prometheus
  logback.xml: |
    <!--
      ============LICENSE_START=======================================================
       Copyright (C) 2021-2022 Nordix Foundation.
      ================================================================================
      Licensed under the Apache License, Version 2.0 (the "License");
      you may not use this file except in compliance with the License.
      You may obtain a copy of the License at
           http://www.apache.org/licenses/LICENSE-2.0
      Unless required by applicable law or agreed to in writing, software
      distributed under the License is distributed on an "AS IS" BASIS,
      WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
      See the License for the specific language governing permissions and
      limitations under the License.
      SPDX-License-Identifier: Apache-2.0
      ============LICENSE_END=========================================================
    -->

    <configuration scan="true" scanPeriod="30 seconds" debug="false">

        <appender name="ErrorOut" class="ch.qos.logback.core.rolling.RollingFileAppender">
            <file>/var/log/onap/policy/pap/error.log</file>
            <rollingPolicy class="ch.qos.logback.core.rolling.SizeAndTimeBasedRollingPolicy">
                <fileNamePattern>/var/log/onap/policy/policy-clamp-runtime-acm/error.%d{yyyy-MM-dd}.%i.log.zip
                </fileNamePattern>
                <maxFileSize>50MB</maxFileSize>
                <maxHistory>30</maxHistory>
                <totalSizeCap>10GB</totalSizeCap>
            </rollingPolicy>
            <filter class="ch.qos.logback.classic.filter.ThresholdFilter">
                <level>WARN</level>
            </filter>
            <encoder>
                <pattern>[%d{yyyy-MM-dd'T'HH:mm:ss.SSS+00:00, UTC}|%level|%logger{0}|%thread] %msg%n</pattern>
            </encoder>
        </appender>

        <appender name="AsyncErrorOut" class="ch.qos.logback.classic.AsyncAppender">
            <appender-ref ref="ErrorOut" />
        </appender>

        <appender name="DebugOut" class="ch.qos.logback.core.rolling.RollingFileAppender">
            <file>/var/log/onap/policy/pap/debug.log</file>
            <rollingPolicy class="ch.qos.logback.core.rolling.SizeAndTimeBasedRollingPolicy">
                <fileNamePattern>/var/log/onap/policy/policy-clamp-runtime-acm/debug.%d{yyyy-MM-dd}.%i.log.zip
                </fileNamePattern>
                <maxFileSize>50MB</maxFileSize>
                <maxHistory>30</maxHistory>
                <totalSizeCap>10GB</totalSizeCap>
            </rollingPolicy>
            <encoder>
                <pattern>[%d{yyyy-MM-dd'T'HH:mm:ss.SSS+00:00, UTC}|%level|%logger{0}|%thread] %msg%n</pattern>
            </encoder>
        </appender>

        <appender name="AsyncDebugOut" class="ch.qos.logback.classic.AsyncAppender">
            <appender-ref ref="DebugOut" />
        </appender>

        <appender name="NetworkOut" class="ch.qos.logback.core.rolling.RollingFileAppender">
            <file>/var/log/onap/policy/policy-clamp-runtime-acm/network.log</file>
            <rollingPolicy class="ch.qos.logback.core.rolling.SizeAndTimeBasedRollingPolicy">
                <fileNamePattern>/var/log/onap/policy/policy-clamp-runtime-acm/network.%d{yyyy-MM-dd}.%i.log.zip
                </fileNamePattern>
                <maxFileSize>50MB</maxFileSize>
                <maxHistory>30</maxHistory>
                <totalSizeCap>10GB</totalSizeCap>
            </rollingPolicy>
            <encoder>
                <pattern>[%d{yyyy-MM-dd'T'HH:mm:ss.SSS+00:00, UTC}|%t]%m%n</pattern>
            </encoder>
        </appender>

        <appender name="AsyncNetworkOut" class="ch.qos.logback.classic.AsyncAppender">
            <appender-ref ref="NetworkOut" />
        </appender>

        <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
            <encoder>
                <Pattern>[%d{yyyy-MM-dd'T'HH:mm:ss.SSS+00:00, UTC}|%level|%logger{0}|%thread] %msg%n</Pattern>
            </encoder>
        </appender>

        <appender name="AsyncStdOut" class="ch.qos.logback.classic.AsyncAppender">
            <appender-ref ref="STDOUT" />
        </appender>

        <logger name="network" level="INFO" additivity="false">
            <appender-ref ref="AsyncNetworkOut" />
            <appender-ref ref="AsyncStdOut" />
        </logger>

        <logger name="org.eclipse.jetty.server.RequestLog" level="info" additivity="false">
            <appender-ref ref="AsyncNetworkOut" />
            <appender-ref ref="AsyncStdOut" />
        </logger>

        <root level="INFO">
            <appender-ref ref="AsyncDebugOut" />
            <appender-ref ref="AsyncErrorOut" />
            <appender-ref ref="AsyncStdOut" />
        </root>

    </configuration>
