# Source: onap/charts/policy/charts/policy-clamp-runtime-acm/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: policy-clamp-runtime-acm
  namespace: onap
  labels:
    app.kubernetes.io/name: policy-clamp-runtime-acm
    helm.sh/chart: policy-clamp-runtime-acm-10.0.0
    app.kubernetes.io/instance: onap
    app.kubernetes.io/managed-by: Helm
spec:
  ports:
  - port: 6969
    targetPort: http-api
    protocol: TCP
    name: http-api
  ipFamilyPolicy: PreferDualStack
  type: ClusterIP
  selector:
    app.kubernetes.io/name: policy-clamp-runtime-acm
    app.kubernetes.io/instance: onap
  sessionAffinity: None
