# Source: onap/charts/sdnc/charts/dgbuilder/charts/certInitializer/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: onap-sdnc-dgbuilder-cert-initializer-add-config
  namespace: onap
  labels:
    app.kubernetes.io/name: sdnc-dgbuilder-cert-initializer
    helm.sh/chart: certInitializer-10.0.0
    app.kubernetes.io/instance: onap
    app.kubernetes.io/managed-by: Helm
data:
  retrieval_check.sh: |
    #!/bin/sh

    echo "*** retrieving passwords for certificates"
    export $(/opt/app/aaf_config/bin/agent.sh local showpass \
      sdnc@sdnc.onap.org sdnc | grep '^c' | xargs -0)
    if [ -z "$cadi_keystore_password_p12" ]
    then
      echo " /!\ certificates retrieval failed"
      exit 1
    fi
    echo "*** password retrieval succeeded"
  aaf-add-config.sh: |
    cd /opt/app/osaaf/local; /opt/app/aaf_config/bin/agent.sh local showpass sdnc@sdnc.onap.org sdnc | grep cadi_keystore_password= | cut -d= -f 2 > /opt/app/osaaf/local/.pass 2>&1 ; cp org.onap.sdnc.crt node-cert.pem; cp org.onap.sdnc.key node-key.pem; chmod go+r node-*.pem
