# Source: onap/charts/dmaap/charts/dmaap-dr-prov/charts/mariadb-init/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: onap-dmaap-dr-mariadb-init
  namespace: onap
  labels:
    app: dmaap-dr-mariadb-init
    chart: mariadb-init-10.0.0
    release: onap
    heritage: Helm
data:
  db_init.sh: |
    #!/bin/sh



    # make sure the script fails if any of commands failed
    set -e

    while read DB ; do
        USER_VAR="MYSQL_USER_$(echo $DB | tr '[:lower:]' '[:upper:]')"
        PASS_VAR="MYSQL_PASSWORD_$(echo $DB | tr '[:lower:]' '[:upper:]')"

        eval USER=\$$USER_VAR
        PASS=$(eval echo -n \$$PASS_VAR | sed -e "s/'/''/g")
        MYSQL_OPTS=" -h "${DB_HOST}" -P "${DB_PORT}" -uroot -p"${MYSQL_ROOT_PASSWORD}

        echo "Creating database ${DB} and user ${USER}..."

        mysql $MYSQL_OPTS -e "CREATE OR REPLACE USER '${USER}'@'%' IDENTIFIED BY '${PASS}'"
        mysql $MYSQL_OPTS -e "CREATE DATABASE IF NOT EXISTS ${DB}"
        mysql $MYSQL_OPTS -e "GRANT ALL PRIVILEGES ON ${DB}.* TO '${USER}'@'%'"

        echo "Created database ${DB} and user ${USER}."
    done <<EOF
    datarouter
    EOF
