# Source: onap/charts/dmaap/charts/dmaap-dr-node/charts/certInitializer/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: onap-dmaap-dr-node-cert-initializer-add-config
  namespace: onap
  labels:
    app.kubernetes.io/name: dmaap-dr-node-cert-initializer
    helm.sh/chart: certInitializer-10.0.0
    app.kubernetes.io/instance: onap
    app.kubernetes.io/managed-by: Helm
data:
  retrieval_check.sh: |
    #!/bin/sh

    echo "*** retrieving passwords for certificates"
    export $(/opt/app/aaf_config/bin/agent.sh local showpass \
      dmaap-dr-node@dmaap-dr.onap.org dmaap-dr-node | grep '^c' | xargs -0)
    if [ -z "$cadi_keystore_password_p12" ]
    then
      echo " /!\ certificates retrieval failed"
      exit 1
    fi
    echo "*** password retrieval succeeded"
  aaf-add-config.sh: |
    echo "cadi_keystore_password_p12=$cadi_keystore_password_p12" > /opt/app/osaaf/local/mycreds.prop echo "cadi_truststore_password=$cadi_truststore_password" >> /opt/app/osaaf/local/mycreds.prop
