# Source: onap/charts/policy/charts/mariadb-galera/templates/metrics-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: onap-policy-mariadb-metrics
  namespace: onap
  labels:
    app.kubernetes.io/name: policy-mariadb
    helm.sh/chart: mariadb-galera-10.0.0
    app.kubernetes.io/instance: onap
    app.kubernetes.io/managed-by: Helm
  annotations:
    prometheus.io/port: "9104"
    prometheus.io/scrape: "true"
spec:
  type: ClusterIP
  ports:
    - name: tcp-metrics
      port: 9104
      targetPort: tcp-metrics
  selector:
    app.kubernetes.io/name: policy-mariadb
    app.kubernetes.io/instance: onap
