# Source: onap/charts/policy/charts/mariadb-galera/templates/pv.yaml
kind: PersistentVolume
apiVersion: v1
metadata:
  name: onap-policy-mariadb--0
  #namespace: onap
  labels:
    app.kubernetes.io/name: policy-mariadb
    helm.sh/chart: mariadb-galera-10.0.0
    app.kubernetes.io/instance: onap
    app.kubernetes.io/managed-by: Helm
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy:
  storageClassName: "onap-policy-mariadb-data"
  hostPath:
    path: /dockerdata-nfs/deployment-1670599359/onap/policy/maria/data-0
