# Source: onap/charts/policy/charts/mariadb-galera/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: onap-policy-mariadb-db-backup-credentials
  namespace: onap
  labels:
    app: policy-mariadb
    chart: mariadb-galera-10.0.0
    release: onap
    heritage: Helm
type: Opaque
stringData:
  login: "mariabackup"
  password: "SD34tyX9"
