# Source: onap/charts/sdnc/templates/pv-data.yaml
kind: PersistentVolume
apiVersion: v1
metadata:
  name: onap-sdnc--0
  namespace: onap
  labels:
    app.kubernetes.io/name: sdnc
    helm.sh/chart: sdnc-10.0.0
    app.kubernetes.io/instance: onap
    app.kubernetes.io/managed-by: Helm
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "onap-sdnc-data"
  hostPath:
    path: /dockerdata-nfs/deployment-1670599359/onap/sdnc/mdsal-0
