# Source: onap/charts/sdnc/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: onap-sdnc-aai-truststore-password
  namespace: onap
  labels:
    app: sdnc
    chart: sdnc-10.0.0
    release: onap
    heritage: Helm
type: Opaque
stringData:
  password: "changeit"
---
# Source: onap/charts/sdnc/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: onap-sdnc-aai-user-creds
  namespace: onap
  labels:
    app: sdnc
    chart: sdnc-10.0.0
    release: onap
    heritage: Helm
type: Opaque
stringData:
  login: "sdnc@sdnc.onap.org"
  password: "demo123456!"
---
# Source: onap/charts/sdnc/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: onap-sdnc-ansible-creds
  namespace: onap
  labels:
    app: sdnc
    chart: sdnc-10.0.0
    release: onap
    heritage: Helm
type: Opaque
stringData:
  login: "sdnc"
  password: "sdnc"
---
# Source: onap/charts/sdnc/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: onap-sdnc-ansible-truststore-password
  namespace: onap
  labels:
    app: sdnc
    chart: sdnc-10.0.0
    release: onap
    heritage: Helm
type: Opaque
stringData:
  password: "changeit"
---
# Source: onap/charts/sdnc/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: onap-sdnc-cds-user-creds
  namespace: onap
  labels:
    app: sdnc
    chart: sdnc-10.0.0
    release: onap
    heritage: Helm
type: Opaque
stringData:
  login: "ccsdkapps"
  password: "ccsdkapps"
---
# Source: onap/charts/sdnc/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: onap-sdnc-db-secret
  namespace: onap
  labels:
    app: sdnc
    chart: sdnc-10.0.0
    release: onap
    heritage: Helm
type: Opaque
stringData:
  login: "sdnctl"
  password: "Zoxm7]RileRexa"
---
# Source: onap/charts/sdnc/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: onap-sdnc-dmaap-authkey
  namespace: onap
  labels:
    app: sdnc
    chart: sdnc-10.0.0
    release: onap
    heritage: Helm
type: Opaque
stringData:
  password: "fs20cKwalJ6ry4kX:7Hqm6BDZK47IKxGRkOPFk33qMYs="
---
# Source: onap/charts/sdnc/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: onap-sdnc-dmaap-proxy-creds
  namespace: onap
  labels:
    app: sdnc
    chart: sdnc-10.0.0
    release: onap
    heritage: Helm
type: Opaque
stringData:
  login: "addUserHere"
  password: "addPasswordHere"
---
# Source: onap/charts/sdnc/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: onap-sdnc-dmaap-user-creds
  namespace: onap
  labels:
    app: sdnc
    chart: sdnc-10.0.0
    release: onap
    heritage: Helm
type: Opaque
stringData:
  login: "admin"
  password: "admin"
---
# Source: onap/charts/sdnc/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: onap-sdnc-honeycomb-user-creds
  namespace: onap
  labels:
    app: sdnc
    chart: sdnc-10.0.0
    release: onap
    heritage: Helm
type: Opaque
stringData:
  login: "admin"
  password: "admin"
---
# Source: onap/charts/sdnc/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: onap-sdnc-keystore-password
  namespace: onap
  labels:
    app: sdnc
    chart: sdnc-10.0.0
    release: onap
    heritage: Helm
type: Opaque
stringData:
  password: "adminadmin"
---
# Source: onap/charts/sdnc/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: onap-sdnc-modeling-user-creds
  namespace: onap
  labels:
    app: sdnc
    chart: sdnc-10.0.0
    release: onap
    heritage: Helm
type: Opaque
stringData:
  login: "ccsdkapps"
  password: "ccsdkapps"
---
# Source: onap/charts/sdnc/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: onap-sdnc-neng-user-creds
  namespace: onap
  labels:
    app: sdnc
    chart: sdnc-10.0.0
    release: onap
    heritage: Helm
type: Opaque
stringData:
  login: "ccsdkapps"
  password: "ccsdkapps"
---
# Source: onap/charts/sdnc/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: onap-sdnc-netbox-apikey
  namespace: onap
  labels:
    app: sdnc
    chart: sdnc-10.0.0
    release: onap
    heritage: Helm
type: Opaque
stringData:
  password: "onceuponatimeiplayedwithnetbox20180814"
---
# Source: onap/charts/sdnc/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: onap-sdnc-odl-creds
  namespace: onap
  labels:
    app: sdnc
    chart: sdnc-10.0.0
    release: onap
    heritage: Helm
type: Opaque
stringData:
  login: "admin"
  password: "Kp8bJ4SXszM0WXlhak3eHlcse2gAw84vaoGGmJvUy2U"
---
# Source: onap/charts/sdnc/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: onap-sdnc-restconf-creds
  namespace: onap
  labels:
    app: sdnc
    chart: sdnc-10.0.0
    release: onap
    heritage: Helm
type: Opaque
stringData:
  login: "admin"
  password: "admin"
---
# Source: onap/charts/sdnc/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: onap-sdnc-scaleout-creds
  namespace: onap
  labels:
    app: sdnc
    chart: sdnc-10.0.0
    release: onap
    heritage: Helm
type: Opaque
stringData:
  login: "admin"
  password: "admin"
---
# Source: onap/charts/sdnc/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: onap-sdnc-so-user-creds
  namespace: onap
  labels:
    app: sdnc
    chart: sdnc-10.0.0
    release: onap
    heritage: Helm
type: Opaque
stringData:
  login: "sdncaBpmn"
  password: "password1$"
---
# Source: onap/charts/sdnc/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: onap-sdnc-truststore-password
  namespace: onap
  labels:
    app: sdnc
    chart: sdnc-10.0.0
    release: onap
    heritage: Helm
type: Opaque
stringData:
  password: "adminadmin"
---
# Source: onap/charts/sdnc/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: onap-sdnc-ves-collector-secret
  namespace: onap
  labels:
    app: sdnc
    chart: sdnc-10.0.0
    release: onap
    heritage: Helm
type: Opaque
stringData:
  login: "sample1"
  password: "sample1"
