# Source: onap/charts/sdnc/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: sdnc
  namespace: onap
  labels:
    app: sdnc
    chart: sdnc-10.0.0
    release: onap
    heritage: Helm
  annotations:
    msb.onap.org/service-info: '[ { "serviceName": "sdnc", "version": "v1", "url": "/", "protocol": "REST", "port": "8282", "visualRange":"1", "path": "/" } ]'
spec:
  type: NodePort
  ports:
    - name: "sdnc-restconf"
      port: 8443
      targetPort: 8443
      nodePort: 30267
  sessionAffinity: ClientIP
  selector:
    app.kubernetes.io/name: sdnc
    app.kubernetes.io/instance: onap
---
# Source: onap/charts/sdnc/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: "sdnc-oam"
  namespace: onap
  labels:
    app: sdnc
    chart: sdnc-10.0.0
    release: onap
    heritage: Helm
spec:
  type: ClusterIP
  ports:
    - name: "sdnc-restconf-alt"
      port: 8282
      targetPort: 8181
    - name: "sdnc-karaf"
      port: 8202
      targetPort: 8101
  selector:
    app.kubernetes.io/name: sdnc
    app.kubernetes.io/instance: onap
---
# Source: onap/charts/sdnc/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: sdnc-cluster
  namespace: onap
  labels:
    app: sdnc
    release: onap
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  ports:
  - name: "sdnc-cluster-port"
    port: 2550
  clusterIP: None
  selector:
    app.kubernetes.io/name: sdnc
    app.kubernetes.io/instance: onap
  sessionAffinity: None
  type: ClusterIP
---
# Source: onap/charts/sdnc/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: sdnc-callhome
  namespace: onap
  labels:
    app: sdnc
    chart: sdnc-10.0.0
    release: onap
    heritage: Helm
spec:
  type: NodePort
  ports:
    - name: "sdnc-callhome"
      port: 6666
      targetPort: 6666
      nodePort: 30266
  selector:
    app.kubernetes.io/name: sdnc
    app.kubernetes.io/instance: onap
