# Source: onap/charts/policy/charts/policy-clamp-ac-k8s-ppnt/templates/service.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: policy-clamp-cl-k8s-ppnt
  namespace: onap
---
# Source: onap/charts/policy/charts/policy-clamp-ac-k8s-ppnt/templates/service.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: onap-policy-clamp-cl-k8s-ppnt-binding
  namespace: onap
  labels:
    app: policy-clamp-ac-k8s-ppnt
    chart: policy-clamp-ac-k8s-ppnt-10.0.0
    release: onap
    heritage: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: policy-clamp-cl-k8s-ppnt
    namespace: onap
