# Source: onap/charts/policy/charts/policy-pap/charts/certInitializer/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: onap-policy-pap-cert-initializer-deployer-creds
  namespace: onap
  labels:
    app: policy-pap-cert-initializer
    chart: certInitializer-10.0.0
    release: onap
    heritage: Helm
type: Opaque
stringData:
  login: "deployer@people.osaaf.org"
  password: "demo123456!"
---
# Source: onap/charts/policy/charts/policy-pap/charts/certInitializer/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: onap-policy-pap-cert-initializer-truststore-creds
  namespace: onap
  labels:
    app: policy-pap-cert-initializer
    chart: certInitializer-10.0.0
    release: onap
    heritage: Helm
type: Opaque
stringData:
  password: "changeit"
