# Source: onap/charts/policy/charts/policy-apex-pdp/charts/serviceAccount/templates/role-binding.yaml
apiVersion: rbac.authorization.k8s.io/v1
# This cluster role binding allows anyone in the "manager" group to read secrets in any namespace.
kind: RoleBinding
metadata:
  name: onap-policy-apex-pdp-read
  namespace: onap
subjects:
- kind: ServiceAccount
  name: onap-policy-apex-pdp-read
roleRef:
  kind: Role
  name: onap-read
  apiGroup: rbac.authorization.k8s.io
